### PR TITLE
Nav for switching between trashmaps

### PR DESCRIPTION
**Pull request by Piepow**
Clicking a button in the top right opens a modal that allows you to navigate to different trashmap sites.

I'm using a branch of my fork because the master branch of that fork currently contains something else I'm working on (namely https://github.com/ddnet/ddnet-trashmap/pull/1). I'm not sure if this will merge properly, so let me know if there are issues.

Ignore the first two commits (https://github.com/timakro/ddnet-trashmap/pull/3/commits/e6e37840130fad0c5acab8f061499ef80fbc854e and https://github.com/timakro/ddnet-trashmap/pull/3/commits/40b66f5d162dd6d0e4da508ef60631284f83ecfd).

### CODE REVIEW

**Comment by timakro** [comment]
Doesn't work for me http://trashmap.ddnet.tw/

**Comment by timakro** [comment]
Thanks! Because of some conflicts and style issues I cherry-picked.

**Comment by timakro** [comment]
@Piepow Which name should I use to credit you in the changelog?

**Comment by Piepow** [comment]
"Oblique" is fine, thanks.

**Comment by timakro** [comment]
Wow, I somehow didn't realize you are the same person who did the new web design, your 3 different names confuse me. :D

**Pull request closed without merging**
