### PR TITLE
New web design

### PR DESCRIPTION
**Pull request by Piepow**
I added some styling and reformatted the HTML of files in the [www](https://github.com/timakro/ddnet-trashmap/tree/master/www) folder. I also fixed some English grammar issues.

Screenshot:
screenshot from 2017-05-06 21-08-04

### CODE REVIEW

**Comment by timakro** [comment]
This looks great! I'm planning to merge this but there are still a few issues:

You should be able to view a list of all saved servers in case you lost your bookmark link. When you create a server the message displayed (on `create_server_handle.php`) doesn't make sense anymore. Instead a button to get to the access page of the server you just created should be shown. 

Additionally it would probably be good to automatically redirect the user after he created a server or changed a setting on the access server page (in case there was no error). The button should still be shown ofcourse in case the users browser doesn't support automatic redirection. So if you also want to implement that I would appreciate it!

I want to give you credits, please tell me what name I should use and if you want me to link some website like I did with my name on the front page. I set up your design here https://kdjqvfi3n.timakro.de/, maybe it helps you understand some of the points I named above. I didn't set up a ssl cert so your browser will probably complain.

Thanks again for your huge effort!

**Comment by Piepow** [comment]
Ok, I fixed both issues.
If you want to credit me you can just use my Teeworlds nick "Oblique"
Also you don't need to add a link/credit on the frontpage for me, but thanks :stuck_out_tongue_closed_eyes:

**Comment by timakro** [comment]
Thanks, there are still a few issues.

Too long content in the tables overlaps:
table_overlap
I had this issue some time ago, this might possibly help you: https://jsfiddle.net/jynuynx9/2/.

The redirection in `access_server_handle.php` doesn't include the query arguments. So it just redirects me to this error page: https://kdjqvfi3n.timakro.de/access_server.php.

When creating a server there is a little bit of delay until the `access_server.php` page notices that and stops displaying there is no such identifier .... So by instantly redirecting the user he will be shown the error page. I have no good solution to tackle this problem. You might use delayed redirection using this method http://stackoverflow.com/a/9877323/3235192 or maybe some javascript magic to delay the redirect.

EDIT: It takes at most 1 second for the `access_server.php` page to realize that the server was created. You might also use the config variable `$config["tickseconds"]` which atm contains 1.

**Comment by timakro** [comment]
Thanks!

**Comment by timakro** [comment]
I can't get the arrow for the breadcrumbs to work:
breadcrumbs
Does this work for you? https://trashmap.timakro.de/create_server.php

**Comment by Piepow** [comment]
No, it doesn't work for me either.
EDIT: I made a new pull request

**Comment by timakro** [comment]
I can't get the arrow for the breadcrumbs to work:
breadcrumbs
Does this work for you? https://trashmap.timakro.de/create_server.php

**Pull request merged**
